!======================================================================================================================!
!
!                    DassFlow Version 2.0
!
!======================================================================================================================!
!
!  Copyright University of Toulouse-INSA - CNRS (France)
!
!  This file is part of the DassFlow software (Data Assimilation for Free Surface Flows).
!  DassFlow is a computational software aiming at simulating geophysical free surface flows.
!  It is designed for Variational Data Assimilation (4D-var) and sensitivity analyses. 
! Inverse capabilities are based on the adjoint code which is generated by 
! a source-to-source algorithmic differentiation (Tapenade software used).
!
!  DassFlow software includes few mostly independent "modules" with common architectures and structures:
!    - DassFlow 2DShallow (shallow water equations in (h,q), finite volumes), i.e. the present code.
!    - DassFlow3D  (non-linear Stokes equations, finite elements, mobile geometries, ALE).
!    - DassFlow 1D (shallow water equations in (S,Q), finite volumes or finite differences), river hydraulics.
!  Please consult the DassFlow webpage for more details: http://www.math.univ-toulouse.fr/DassFlow
!
! You have used DassFlow in an article, a scientific document etc ?  How to cite us ? Please consult the webpage.
! 
!  Many people have contributed to the DassFlow developments from the initial version to the latest ones.
!  Current main developers or scientific contributers are:
!               P. Brisset (CNES & Mathematics Institute of Toulouse & INSA Toulouse)
!               F. Couderc (CNRS & Mathematics Institute of Toulouse IMT)
!               P.-A. Garambois (INSA & ICUBE Strasbourg)
!               J. Monnier (INSA & Mathematics Institute of Toulouse IMT).
!               J.-P. Vila (INSA & Mathematics Institute of Toulouse IMT).
!  and former other developers (R. Madec, M. Honnorat and J. Marin).
!
!  Scientific contact : jerome.monnier@insa-toulouse.fr
!  Technical  contacts : frederic.couderc@math.univ-toulouse.fr, pierre.brisset@insa-toulouse.fr
!
!  This software is governed by the CeCILL license under French law and abiding by the rules of distribution
!  of free software. You can use, modify and/or redistribute the software under the terms of the CeCILL license
!  as circulated by CEA, CNRS and INRIA at the following URL: "http://www.cecill.info".
!
!  As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the
!  license, users are provided only with a limited warranty and the software's author, the holder of the economic
!  rights, and the successive licensors have only limited liability.
!
!  In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or
!  developing or reproducing the software by the user in light of its specific status of free software, that may
!  mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and
!  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the
!  software's suitability as regards their requirements in conditions enabling the security of their systems and/or
!  data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
!
!  The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you
!  accept its terms.
!
!======================================================================================================================!
!> \file m_linear_algebra.f90
!! \brief This file includes m_linear_algebra module.
!! \details The file includes only m_linear_algebra module (see doc m_linear_algebra module).

!**********************************************************************************************************************!
!**********************************************************************************************************************!
!
!  Module m_linear_algebra.f90
!
!**********************************************************************************************************************!
!**********************************************************************************************************************!

!> Module m_linear_algebra.
!!
!! \details This module define algebra used (2D vector structure).
MODULE m_linear_algebra

   USE m_common

   implicit none

!======================================================================================================================!
!  2D Vector Structure
!======================================================================================================================!
   !> Structure of a 2D Vector. 
   !!
   !! \details This type is used for the definition of vector of size 2 ( Coordinates \f$(x,y)\f$ for example).
   TYPE vec2d
      real(rp)  ::  x !<Coordinate \f$x\f$ of the vector.
      real(rp)  ::  y !<Coordinate \f$y\f$ of the vector.
   END TYPE vec2d

!======================================================================================================================!
!  Dense matrix
!======================================================================================================================!
   !> Structure of a dense Matrix.
   TYPE matrix
      !> Data array (COLUMN MAJOR : column index, row index)
      real(rp), dimension(:, :), allocatable  ::  m
   END TYPE matrix
   


CONTAINS


!**********************************************************************************************************************!
!**********************************************************************************************************************!
!
!  Compute Cholesky decomposition for a dense matrix
!
!**********************************************************************************************************************!
!**********************************************************************************************************************!
   !> Compute the Cholesky decomposition in place (lower triangular part is L, upper triangular part is L.T)
   !!
   !! \param[in] n Size of the Matrix A
   !! \param[inout] A Matrix A in dense format
   SUBROUTINE cholesky_inplace( n, A )

      !================================================================================================================!
      !  Interface Variables
      !================================================================================================================!

      integer(ip), intent(in)  ::  n

      real(rp), dimension(n,n)  ::  A

      !================================================================================================================!
      !  Local Variables
      !================================================================================================================!

      integer(ip)  ::  i, j
      
      real(rp) :: sum1
      
      real(rp), dimension(n)  ::  diag

      !================================================================================================================!
      !  Compute diagonal values and lower trianguar part
      !================================================================================================================!

      do i = 1 , n
      
         do j = i , n
         
            sum1 = A( j , i )
            
            do k = i-1, 1 , -1
            
               sum1 = sum1 - A( k , i ) * A( k , j )
               
            end do
            
            if( i == j ) then
            
               if( sum1 <= 0.0 ) then
               
                  write(*,*) "[ ERROR ] Cholesky decomposition failed on sum1=", sum1
                  stop
                  
               end if
               
               diag( i ) = sqrt( sum1 )
               
            else
            
               A( i , j ) = sum1 / diag( i )

            end if

         end do
         
      end do

      !================================================================================================================!
      !  Apply computed diagonal values
      !================================================================================================================!
      
      do i = 1 , n
      
         A( i , i) = diag( i )
         
      end do
! 
!       !================================================================================================================!
!       !  Compute upper part by symmetry
!       !================================================================================================================!
!       
!       do i = 1 , n
!       
!          do j = i+1 , n
!       
!             A( j , i ) = A( i , j )
! 
!          end do
!          
!       end do

      !================================================================================================================!
      !  Put zeros on upper part
      !================================================================================================================!
      
      do i = 1 , n
      
         do j = i+1 , n
      
            A( j , i ) = 0.0_rp

         end do
         
      end do

   END SUBROUTINE cholesky_inplace
! 
! 
! !**********************************************************************************************************************!
! !**********************************************************************************************************************!
! !
! !  Compute Cholesky decomposition for a dense matrix
! !
! !**********************************************************************************************************************!
! !**********************************************************************************************************************!
!    !> Compute the Cholesky decomposition in place (lower triangular part is L, upper triangular part is L.T)
!    !!
!    !! \param[in] n Size of the Matrix A
!    !! \param[in] mat Matrix A in dense format
!    SUBROUTINE cholesky_inplace( n, mat )
! 
!       !================================================================================================================!
!       !  Interface Variables
!       !================================================================================================================!
! 
!       integer(ip), intent(in)  ::  n
! 
!       type(matrix)  ::  mat
! 
!       !================================================================================================================!
!       !  Interface Variables
!       !================================================================================================================!
! 
!       integer(ip)  ::  i, j
! 
!       !================================================================================================================!
!       !  Compute lower trianguar part
!       !================================================================================================================!
! 
!       mat%m(1,1) = sqrt(mat%m(1,1))
!       
!       do j = 2, n
!       
!          mat%m(1,j) = mat%m(j,1) / mat%m(1,1)
!          
!       end do
!       
!       do i = 2, n
!       
!          do k = 1, i-1
!          
!             mat%m(i,i) = mat%m(i,i) - mat%m(k,i)**2
!             
!          end do
!          
!          mat%m(i,i) = sqrt(mat%m(i,i))
!          
!          do j = i+1, n
!             
!             mat%m(i,j) = mat%m(j,i)
!             
!             do k = 1, i-1
!             
!                mat%m(i,j) = mat%m(i,j) - mat%m(k,i) * mat%m(k,j)
!                
!             end do
!             
!             mat%m(i,j) = mat%m(i,j) / mat%m(i,i)
!             
!          end do
! 
!       end do
! 
!       !================================================================================================================!
!       !  Compute upper triangular part (symmetricity)
!       !================================================================================================================!
! 
!       do i = 1, n
!       
!          do j = i+1, n
!       
!             mat%m(j,i) = mat%m(i,j)
!             
!          end do
!          
!       end do
! 
!    END SUBROUTINE cholesky_inplace


!**********************************************************************************************************************!
!**********************************************************************************************************************!
!
!  Solve Ax=b where A is a Cholesky decomposition
!
!**********************************************************************************************************************!
!**********************************************************************************************************************!
   !> Solve Ax=b using the Cholesky decomposition of A (lower triangular part is L, upper triangular part is L.T)
   !!
   !! \param[in] n Size of the Matrix A
   !! \param[in] mat Matrix A in dense format
   !! \param[in] b Right hand side vector
   !! \param[in] x Solution
   SUBROUTINE solve_using_cholesky_inplace( n, mat, b, x )

      !================================================================================================================!
      !  Interface Variables
      !================================================================================================================!

      integer(ip), intent(in)  ::  n

      type(matrix), intent(in) ::  mat
      
      real(rp), dimension(n), intent(in)  ::  b
      
      real(rp), dimension(n), intent(out)  ::  x

      !================================================================================================================!
      !  
      !================================================================================================================!

      integer(ip)  ::  i, j
      real(rp), dimension(n)  ::  y

      !================================================================================================================!
      !  Step 1 : solve Ly = b
      !================================================================================================================!
      y(1) = b(1) / mat%m(1,1)
      do i = 2, n
      
         y(i) = b(i)
         
         do j = 1, i-1
         
            y(i) = y(i) - mat%m(j,i) * b(j)
         
         end do
         y(i) = y(i) / mat%m(i,i)
        
      end do

      !================================================================================================================!
      !  Step 2 : solve L'x = y
      !================================================================================================================!
      x(n) = y(n) / mat%m(n,n)
      do i = n-1, 1, -1
      
         x(i) = y(i)
         
         do j = i+1, n
         
            x(i) = x(i) - mat%m(j,i) * y(j)
         
         end do
         x(i) = x(i) / mat%m(i,i)
        
      end do

   END SUBROUTINE solve_using_cholesky_inplace

END MODULE m_linear_algebra
